### ISSUE TITLE
[toc] Performance Improvements

### ISSUE THREAD

**Issue by vnphanquang** [vnphanquang/svelte-put#109]
## Context

As `toc@2.0.0` was released, almost everything was re-implemented from the ground up. This issue lists potential performance improvement

## Todos

- [x] reduce to use only one `IntersectionObserver` instead of one for each matching elements <- https://github.com/vnphanquang/svelte-put/commit/60c2029db21ba6b6a478bff25fd4a8d39c07038f
- [x] run observe operations async <- https://github.com/vnphanquang/svelte-put/commit/a8cd5c2dce7af3aa382a38e69d3c357381e7087b
- [x] use simple callback instead of store for tracking active element <- https://github.com/vnphanquang/svelte-put/commit/d04d44e010cbe74f63c5304451524902c68036c7
