### ISSUE TITLE
[docs] Scope general info in `Overview` sections

### ISSUE THREAD

**Issue by vnphanquang** [vnphanquang/svelte-put#162]
## Context

Taking inspiration from [GrailUI](https://grail-ui.vercel.app/svelte/getting-started), let's introduce an `Overview` group in the left-side that contains general information

## Todos

- [x] Add `Overview` section
- [x] Try setting section as uppercase, ex OVERVIEW
- [x] Move `Introduction` into `OVERVIEW`
- [x] Add `Design`:
    - [x] with type-safe / for typescript user
    - [x] try to be headless whenever possible
    - [x] minimal, few dependencies as possible
- [x] Add `Guidelines`(?):
    - [x] Action usage notice
    - [x] Typescript support
    - [x] API section?
