### ISSUE TITLE
Bootstrap a Documentation Site - Master Issue

### ISSUE THREAD

**Issue by vnphanquang** [vnphanquang/svelte-put#61]
Create a dedicated doc site for all documentation and examples, as docs through markdowns in github seems hard to follow

Sites to steal from:

- https://xstate.js.org
- https://daisyui.com/
- https://kit.svelte.dev/
- https://tailwindcss.com/
- https://tanstack.com/table/v8/
- https://docs.astro.build/
- https://turbo.build/repo/docs
- vue/vite eco:
  - https://vitest.dev/
  - https://vuejs.org/
  - https://histoire.dev/
  - https://vitejs.dev/

Todos:

- [x] deploy to vercel?
- [x] domain: `svelte-put.vnphanquang.com`?
- [x] use [MDSvex](https://github.com/pngwn/MDsveX) => yes
- [x] import code as raw string for showing code in examples & documentations (solution: use [vite's `?raw` import query](https://vitejs.dev/guide/assets.html#importing-asset-as-string))
- [x] how to include the extracted api to site automatically (API Reference sections)? ❌❌ -> for now just include link to api on github.
- [x] embedded svelte repl? but what about typescript? -> let's not embed, link through badge or implement dedicated playground in site
- [x] full set of favicons
- [x] `manifest.json` and full support for PWA
- [x] code block syntax highlighting with [svelte-highlight](https://github.com/metonym/svelte-highlight)
- [ ] reorganize components into atomic design pattern structure

Landing animation inspiration:

- https://codepen.io/jh3y/pen/XWaGEgO?editors=1100
- https://codepen.io/desandro/pen/KRWjzm

**Comment by vnphanquang** [comment]
Improve `Code` component following pattern from vercel docs ([example here](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation)).

- [ ] add top bar with an optional file name as prop
- [ ] move copy icon to the top bar
- [ ] add shadow?

**Comment by vnphanquang** [comment]
package docs:
  - [ ] `svelte-put/avatar`
  - [x] `svelte-put/clickoutside`
  - [ ] `svelte-put/copy`
  - [ ] `svelte-put/intersect`
  - [ ] `svelte-put/modal`
  - [ ] `svelte-put/movable`
  - [ ] `svelte-put/preprocess-auto-slug`
  - [ ] `svelte-put/select`
  - [ ] `svelte-put/shortcut`
  - [ ] `svelte-put/toc`

**Comment by vnphanquang** [comment]
"On this page" automatically nav section
  - [svelteness/kit-docs/OnThisPage.svelte](https://github.com/svelteness/kit-docs/blob/424730f9917aae1ff53c854a57b2189c23e8e62c/packages/kit-docs/src/lib/components/layout/OnThisPage.svelte)
  - [sveltejs/kit/OnThisPage.svelte](https://github.com/sveltejs/kit/blob/acbbf12afdad0067f7d38cfb8d324c96bd802038/sites/kit.svelte.dev/src/routes/docs/%5Bslug%5D/OnThisPage.svelte)

**Comment by vnphanquang** [comment]
dynamic OG image: https://github.com/vercel/og-image
  - [ ] https://vercel.com/blog/introducing-vercel-og-image-generation-fast-dynamic-social-card-images
  - [ ] https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation
  - [ ] https://dev.to/theether0/dynamic-og-image-with-sveltekit-and-satori-4438
  - [ ] image 3d card elevated like hero of this: https://automate.io/

**Comment by vnphanquang** [comment]
[algolia](https://www.algolia.com/) search integration???

**Comment by vnphanquang** [comment]
- [ ] tooltip to explain badge on sidebar (`dev`, `new`, `beta`, `flux`)

**Comment by vnphanquang** [comment]
- [ ] Responsive support (tablet / mobile)

**Comment by vnphanquang** [comment]
- [ ] Add a `edit this page on github` button somewhere on each page

**Comment by vnphanquang** [comment]
- [x] setup vercel analytics

**Comment by vnphanquang** [comment]
- [ ] error page

**Comment by vnphanquang** [comment]
- [ ] fix `_blank` anchors

**Comment by vnphanquang** [comment]
- [ ] `humans.txt`

resources: 

- https://codeburst.io/all-about-humans-humans-txt-actually-f571d37f92d2
- https://humanstxt.org/Standard.html
